export const formTemplates = [
  {
    formName: 'Aerial Inspection Form',
    formId: '694dd4388e784ef29df97bdd5734ff6d',
    fields: [
      {
        IDX: 165,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: 'a9f7d76b7048415884c88a58ba38c42d',
        categoryOrder: 1,
        fieldOrder: 2,
        category: 'General',
        title: 'Accessibility to Asset',
        fieldName: 'access',
        fieldType: 'text',
        dataType: 'text',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: null,
        requiresPhoto: 1,
        visible: 1,
        inputReq: 0,
        defautVal: null,
      },
      {
        IDX: 166,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: '10d793fde39d4450964acaaa69d8eb63',
        categoryOrder: 1,
        fieldOrder: 3,
        category: 'General',
        title: 'Line Shape',
        fieldName: 'pipeshape',
        fieldType: 'text',
        dataType: 'text',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: null,
        requiresPhoto: 0,
        visible: 1,
        inputReq: 0,
        defautVal: null,
      },
      {
        IDX: 167,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: '2f98776082664ecd966fe89de3e36b86',
        categoryOrder: 1,
        fieldOrder: 4,
        category: 'General',
        title: 'Width/Diameter',
        fieldName: 'width_dia',
        fieldType: 'numberInt',
        dataType: 'numberInt',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: null,
        requiresPhoto: 0,
        visible: 1,
        inputReq: 0,
        defautVal: null,
      },
      {
        IDX: 168,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: 'eb2eab54eae14086b2d8cd76c37c1701',
        categoryOrder: 1,
        fieldOrder: 5,
        category: 'General',
        title: 'Height',
        fieldName: 'height',
        fieldType: 'numberInt',
        dataType: 'numberInt',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: null,
        requiresPhoto: 0,
        visible: 1,
        inputReq: 0,
        defautVal: null,
      },
      {
        IDX: 169,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: '811909e6690d4bac98d349b25b49b912',
        categoryOrder: 1,
        fieldOrder: 6,
        category: 'General',
        title: 'Material',
        fieldName: 'material',
        fieldType: 'text',
        dataType: 'text',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: null,
        requiresPhoto: 0,
        visible: 1,
        inputReq: 0,
        defautVal: null,
      },
      {
        IDX: 170,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: '64f77d075d91418b816b02e6f29040e4',
        categoryOrder: 1,
        fieldOrder: 7,
        category: 'General',
        title: 'Max Unsupported Span Length',
        fieldName: 'maxspan',
        fieldType: 'numberInt',
        dataType: 'numberInt',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: null,
        requiresPhoto: 0,
        visible: 1,
        inputReq: 0,
        defautVal: null,
      },
      {
        IDX: 171,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: 'd243c9a0a9df431683828829eb07ce0c',
        categoryOrder: 1,
        fieldOrder: 8,
        category: 'General',
        title: 'Photos',
        fieldName: 'photo',
        fieldType: 'photo',
        dataType: 'photo',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: null,
        requiresPhoto: 0,
        visible: 1,
        inputReq: 0,
        defautVal: null,
      },
      {
        IDX: 172,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: 'f789b0dfc1a343179356a956b5ffb7a7',
        categoryOrder: 2,
        fieldOrder: 1,
        category: 'Condition',
        title: 'General Condition',
        fieldName: 'cGeneral',
        fieldType: 'select',
        dataType: 'text',
        dropVals: '{"0":"0","1":"1","2":"2","3":"3","4":"4","5":"5"}',
        fillMethod: null,
        commentField: 1,
        commentFieldName: 'cGeneralNote',
        helpText:
          'General pipe condition (including corrosion, paint/covering, stripping)',
        requiresPhoto: 1,
        visible: 1,
        inputReq: 0,
        defautVal: '0',
      },
      {
        IDX: 173,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: '146f31649033491ba92fe83794b66e31',
        categoryOrder: 2,
        fieldOrder: 2,
        category: 'Condition',
        title: 'Condition of Structures',
        fieldName: 'cStructure',
        fieldType: 'select',
        dataType: 'text',
        dropVals: '{"0":"0","1":"1","2":"2","3":"3","4":"4","5":"5"}',
        fillMethod: null,
        commentField: 1,
        commentFieldName: 'cStructureNote',
        helpText: 'General condition of any concrete structures',
        requiresPhoto: 1,
        visible: 1,
        inputReq: 0,
        defautVal: '0',
      },
      {
        IDX: 174,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: '5ddceedde979428d845d5955cb360409',
        categoryOrder: 2,
        fieldOrder: 3,
        category: 'Condition',
        title: 'Gibault Condition',
        fieldName: 'cGibault',
        fieldType: 'select',
        dataType: 'text',
        dropVals: '{"0":"0","1":"1","2":"2","3":"3","4":"4","5":"5"}',
        fillMethod: null,
        commentField: 1,
        commentFieldName: 'cGibaultNote',
        helpText: 'General condition of any gibault joints/couplers',
        requiresPhoto: 1,
        visible: 1,
        inputReq: 0,
        defautVal: '0',
      },
      {
        IDX: 175,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: '4e0dcd7d5916491281297979b93bee76',
        categoryOrder: 2,
        fieldOrder: 4,
        category: 'Condition',
        title: 'Metal Fixture Condition',
        fieldName: 'cMetal',
        fieldType: 'select',
        dataType: 'text',
        dropVals: '{"0":"0","1":"1","2":"2","3":"3","4":"4","5":"5"}',
        fillMethod: null,
        commentField: 1,
        commentFieldName: 'cMetalNote',
        helpText: 'General condition of any metal fixtures',
        requiresPhoto: 1,
        visible: 1,
        inputReq: 0,
        defautVal: '0',
      },
      {
        IDX: 176,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: 'd23d458097f84459a2148fd1da87dfb6',
        categoryOrder: 2,
        fieldOrder: 5,
        category: 'Condition',
        title: 'Timber Structure Condition',
        fieldName: 'cTimber',
        fieldType: 'select',
        dataType: 'text',
        dropVals: '{"0":"0","1":"1","2":"2","3":"3","4":"4","5":"5"}',
        fillMethod: null,
        commentField: 1,
        commentFieldName: 'cTimberNote',
        helpText: 'General condition of any timber strctures',
        requiresPhoto: 1,
        visible: 1,
        inputReq: 0,
        defautVal: '0',
      },
      {
        IDX: 177,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: 'c17b11508abd4a7cbc469941fdb01bd3',
        categoryOrder: 2,
        fieldOrder: 6,
        category: 'Condition',
        title: 'Leakage',
        fieldName: 'leakage',
        fieldType: 'select',
        dataType: 'text',
        dropVals:
          '{"Yes":"Yes","No":"No","Unknown":"Unknown","Not Applicable":"Not Applicable"}',
        fillMethod: null,
        commentField: 1,
        commentFieldName: null,
        helpText: 'Any leakage from pipe',
        requiresPhoto: 1,
        visible: 1,
        inputReq: 0,
        defautVal: 'Unknown',
      },
      {
        IDX: 178,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: 'fff22b81e37e41b6b4ea8843edd22f07',
        categoryOrder: 1,
        fieldOrder: 1,
        category: 'General',
        title: 'Inspection Date',
        fieldName: 'inspdate',
        fieldType: 'datetime',
        dataType: 'datetime',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: null,
        requiresPhoto: 0,
        visible: 1,
        inputReq: 1,
        defautVal: null,
      },
      {
        IDX: 179,
        formid: '694dd4388e784ef29df97bdd5734ff6d',
        formName: 'Aerial Inspection',
        systemid: null,
        fieldid: 'fa7ea4b236e849c2a0b4e840d807644a',
        categoryOrder: 2,
        fieldOrder: 7,
        category: 'Condition',
        title: 'External Debris',
        fieldName: 'debris',
        fieldType: 'select',
        dataType: 'text',
        dropVals:
          '{"Yes":"Yes","No":"No","Unknown":"Unknown","Not Applicable":"Not Applicable"}',
        fillMethod: null,
        commentField: 1,
        commentFieldName: 'debrisNote',
        helpText: 'Any debris present on or arround the pipe',
        requiresPhoto: 1,
        visible: 1,
        inputReq: 0,
        defautVal: 'Unknown',
      },
    ],
  },
  {
    formName: 'Test Contact Form',
    formId: 'a7300a7b356c483c943a5be6624c14a2',
    fields: [
      {
        IDX: 201,
        formid: 'a7300a7b356c483c943a5be6624c14a2',
        formName: 'Contact Form',
        systemid: null,
        fieldid: 'fld_name',
        categoryOrder: 1,
        fieldOrder: 1,
        category: 'Personal Details',
        title: 'Full Name',
        fieldName: 'full_name',
        fieldType: 'text',
        dataType: 'text',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: 'Your legal name, please.',
        requiresPhoto: 0,
        visible: 1,
        inputReq: 1,
        defautVal: null,
      },
      {
        IDX: 202,
        formid: 'a7300a7b356c483c943a5be6624c14a2',
        formName: 'Contact Form',
        systemid: null,
        fieldid: 'fld_email',
        categoryOrder: 1,
        fieldOrder: 2,
        category: 'Personal Details',
        title: 'Email Address',
        fieldName: 'email',
        fieldType: 'text',
        dataType: 'email',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: 'We’ll never send you spam.',
        requiresPhoto: 0,
        visible: 1,
        inputReq: 1,
        defautVal: null,
      },
      {
        IDX: 203,
        formid: 'a7300a7b356c483c943a5be6624c14a2',
        formName: 'Contact Form',
        systemid: null,
        fieldid: 'fld_subject',
        categoryOrder: 2,
        fieldOrder: 1,
        category: 'Message Info',
        title: 'Subject',
        fieldName: 'subject',
        fieldType: 'select',
        dataType: 'text',
        dropVals:
          '{"General Inquiry":"General Inquiry","Support":"Support","Feedback":"Feedback","Other":"Other"}',
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: 'What’s this about?',
        requiresPhoto: 0,
        visible: 1,
        inputReq: 1,
        defautVal: 'General Inquiry',
      },
      {
        IDX: 204,
        formid: 'a7300a7b356c483c943a5be6624c14a2',
        formName: 'Contact Form',
        systemid: null,
        fieldid: 'fld_msg',
        categoryOrder: 2,
        fieldOrder: 2,
        category: 'Message Info',
        title: 'Your Message',
        fieldName: 'message',
        fieldType: 'textarea',
        dataType: 'text',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: 'The longer the better. (Within reason.)',
        requiresPhoto: 0,
        visible: 1,
        inputReq: 1,
        defautVal: null,
      },
      {
        IDX: 205,
        formid: 'a7300a7b356c483c943a5be6624c14a2',
        formName: 'Contact Form',
        systemid: null,
        fieldid: 'fld_contact_pref',
        categoryOrder: 3,
        fieldOrder: 1,
        category: 'Preferences',
        title: 'Preferred Contact Method',
        fieldName: 'contact_method',
        fieldType: 'select',
        dataType: 'text',
        dropVals: '{"Email":"Email","Phone":"Phone","SMS":"SMS"}',
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: 'How should we get in touch?',
        requiresPhoto: 0,
        visible: 1,
        inputReq: 0,
        defautVal: 'Email',
      },
      {
        IDX: 206,
        formid: 'a7300a7b356c483c943a5be6624c14a2',
        formName: 'Contact Form',
        systemid: null,
        fieldid: 'fld_file',
        categoryOrder: 4,
        fieldOrder: 1,
        category: 'Attachments',
        title: 'Attach File (optional)',
        fieldName: 'attachment',
        fieldType: 'file',
        dataType: 'file',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: 'PDF, DOCX, JPG, etc.',
        requiresPhoto: 0,
        visible: 1,
        inputReq: 0,
        defautVal: null,
      },
      {
        IDX: 207,
        formid: 'a7300a7b356c483c943a5be6624c14a2',
        formName: 'Contact Form',
        systemid: null,
        fieldid: 'fld_subscribe',
        categoryOrder: 3,
        fieldOrder: 2,
        category: 'Preferences',
        title: 'Subscribe to Newsletter?',
        fieldName: 'newsletter',
        fieldType: 'checkbox',
        dataType: 'boolean',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: 'We send good vibes and bad puns.',
        requiresPhoto: 0,
        visible: 1,
        inputReq: 0,
        defautVal: null,
      },
      {
        IDX: 208,
        formid: 'a7300a7b356c483c943a5be6624c14a2',
        formName: 'Contact Form',
        systemid: null,
        fieldid: 'fld_date',
        categoryOrder: 1,
        fieldOrder: 3,
        category: 'Personal Details',
        title: 'Preferred Contact Date',
        fieldName: 'contact_date',
        fieldType: 'datetime',
        dataType: 'datetime',
        dropVals: null,
        fillMethod: null,
        commentField: 0,
        commentFieldName: null,
        helpText: 'Pick a day that works for you.',
        requiresPhoto: 0,
        visible: 1,
        inputReq: 0,
        defautVal: null,
      },
    ],
  },
];
